openapi: 3.0.3
info:
  title: Order API
  version: 1.0.0

paths:
  /orders:
    post:
      operationId: PostOrders
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateOrder'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'

  /orders/{id}:
    get:
      operationId: GetOrdersId
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'

components:
  schemas:
    OrderItem:
      type: object
      required: [product_id, quantity]
      properties:
        product_id: { type: string }
        quantity:   { type: integer, format: int32, minimum: 1 }

    CreateOrder:
      type: object
      required: [user_id, items]
      properties:
        user_id: { type: string }
        items:
          type: array
          minItems: 1
          items: { $ref: '#/components/schemas/OrderItem' }

    Order:
      type: object
      required: [id, user_id, status, items]
      properties:
        id:      { type: string }
        user_id: { type: string }
        status:  { type: string, enum: [paid, rejected, pending] }
        items:
          type: array
          items: { $ref: '#/components/schemas/OrderItem' }